-- MySQL Database Export
-- Database: valve_test_suite
-- Export Date: 2025-10-03T16:36:31.817Z
-- Generated by Node.js export script

SET FOREIGN_KEY_CHECKS = 0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;

-- Create database
CREATE DATABASE IF NOT EXISTS `valve_test_suite` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `valve_test_suite`;

-- Table structure for `pop_test_headers`
DROP TABLE IF EXISTS `pop_test_headers`;
CREATE TABLE `pop_test_headers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `report_number` varchar(50) NOT NULL,
  `operator_id` int NOT NULL,
  `operator_name` varchar(100) NOT NULL,
  `company` varchar(100) NOT NULL,
  `equipment_no` varchar(50) NOT NULL,
  `ref_no` varchar(50) NOT NULL,
  `test_medium` varchar(50) DEFAULT 'N2',
  `ambient_temp` varchar(50) DEFAULT '(23±5)°C',
  `test_date` date NOT NULL,
  `next_test_date` date DEFAULT NULL,
  `master_pressure_gauge` varchar(50) DEFAULT '22024750',
  `calibration_cert` varchar(50) DEFAULT 'CMS-5009-24',
  `gauge_due_date` date DEFAULT NULL,
  `range` varchar(50) DEFAULT '(0~600) psi',
  `make_model` varchar(50) DEFAULT 'Winter/PFP',
  `calibrate_company` varchar(50) DEFAULT 'Caltek Pte Ltd',
  `remarks` text,
  `attachments` json DEFAULT NULL,
  `status` enum('pending','approved','rejected') DEFAULT 'pending',
  `approved_by` int DEFAULT NULL,
  `approved_at` timestamp NULL DEFAULT NULL,
  `rejection_reason` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `report_number` (`report_number`),
  KEY `approved_by` (`approved_by`),
  KEY `idx_report_number` (`report_number`),
  KEY `idx_equipment_no` (`equipment_no`),
  KEY `idx_ref_no` (`ref_no`),
  KEY `idx_operator_id` (`operator_id`),
  KEY `idx_status` (`status`),
  KEY `idx_test_date` (`test_date`),
  CONSTRAINT `pop_test_headers_ibfk_1` FOREIGN KEY (`operator_id`) REFERENCES `users` (`id`) ON DELETE CASCADE,
  CONSTRAINT `pop_test_headers_ibfk_2` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table structure for `pop_test_valves`
DROP TABLE IF EXISTS `pop_test_valves`;
CREATE TABLE `pop_test_valves` (
  `id` int NOT NULL AUTO_INCREMENT,
  `header_id` int NOT NULL,
  `valve_index` int NOT NULL,
  `serial_number` varchar(100) NOT NULL,
  `brand` varchar(100) NOT NULL,
  `year_of_manufacture` varchar(7) NOT NULL,
  `material_type` varchar(100) NOT NULL,
  `model` varchar(100) NOT NULL,
  `inlet_size` varchar(50) NOT NULL,
  `outlet_size` varchar(50) NOT NULL,
  `coefficient_discharge` varchar(50) NOT NULL,
  `set_pressure` decimal(10,2) NOT NULL,
  `input_pressure` decimal(10,2) NOT NULL,
  `pop_pressure` decimal(10,2) NOT NULL,
  `reset_pressure` decimal(10,2) NOT NULL,
  `pop_tolerance` varchar(20) DEFAULT NULL,
  `reset_tolerance` varchar(20) DEFAULT NULL,
  `pop_result` varchar(20) DEFAULT NULL,
  `reset_result` varchar(20) DEFAULT NULL,
  `overall_result` varchar(20) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_header_id` (`header_id`),
  KEY `idx_serial_number` (`serial_number`),
  KEY `idx_overall_result` (`overall_result`),
  CONSTRAINT `pop_test_valves_ibfk_1` FOREIGN KEY (`header_id`) REFERENCES `pop_test_headers` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table structure for `test_reports`
DROP TABLE IF EXISTS `test_reports`;
CREATE TABLE `test_reports` (
  `id` int NOT NULL AUTO_INCREMENT,
  `report_number` varchar(50) NOT NULL,
  `operator_id` int NOT NULL,
  `operator_name` varchar(100) NOT NULL,
  `company` varchar(100) NOT NULL,
  `valve_tag_number` varchar(100) DEFAULT NULL,
  `valve_manufacturer` varchar(100) DEFAULT NULL,
  `valve_model` varchar(100) DEFAULT NULL,
  `valve_size` varchar(50) DEFAULT NULL,
  `valve_type` varchar(100) DEFAULT NULL,
  `set_pressure` decimal(10,2) DEFAULT NULL,
  `set_pressure_unit` varchar(20) DEFAULT NULL,
  `test_date` date NOT NULL,
  `test_location` varchar(200) DEFAULT NULL,
  `test_medium` varchar(100) DEFAULT NULL,
  `test_temperature` decimal(10,2) DEFAULT NULL,
  `test_temperature_unit` varchar(20) DEFAULT NULL,
  `opening_pressure` decimal(10,2) DEFAULT NULL,
  `closing_pressure` decimal(10,2) DEFAULT NULL,
  `seat_tightness` varchar(100) DEFAULT NULL,
  `test_result` enum('pass','fail','conditional') DEFAULT 'pass',
  `remarks` text,
  `attachments` json DEFAULT NULL,
  `status` enum('pending','approved','rejected') DEFAULT 'pending',
  `approved_by` int DEFAULT NULL,
  `approved_at` timestamp NULL DEFAULT NULL,
  `rejection_reason` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `report_number` (`report_number`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table structure for `users`
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(50) NOT NULL,
  `password` varchar(255) NOT NULL,
  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `role` enum('operator','admin','supervisor') NOT NULL DEFAULT 'operator',
  `company` varchar(100) NOT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `last_login` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  UNIQUE KEY `email` (`email`),
  KEY `idx_username` (`username`),
  KEY `idx_email` (`email`),
  KEY `idx_role` (`role`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table structure for `valve_bmm_combinations`
DROP TABLE IF EXISTS `valve_bmm_combinations`;
CREATE TABLE `valve_bmm_combinations` (
  `id` int NOT NULL AUTO_INCREMENT,
  `brand_id` int NOT NULL,
  `model_id` int NOT NULL,
  `material_id` int NOT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_bmm` (`brand_id`,`model_id`,`material_id`),
  KEY `model_id` (`model_id`),
  KEY `material_id` (`material_id`),
  CONSTRAINT `valve_bmm_combinations_ibfk_1` FOREIGN KEY (`brand_id`) REFERENCES `valve_brands` (`id`) ON DELETE CASCADE,
  CONSTRAINT `valve_bmm_combinations_ibfk_2` FOREIGN KEY (`model_id`) REFERENCES `valve_models` (`id`) ON DELETE CASCADE,
  CONSTRAINT `valve_bmm_combinations_ibfk_3` FOREIGN KEY (`material_id`) REFERENCES `valve_materials` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table structure for `valve_brands`
DROP TABLE IF EXISTS `valve_brands`;
CREATE TABLE `valve_brands` (
  `id` int NOT NULL AUTO_INCREMENT,
  `brand_name` varchar(100) NOT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `brand_name` (`brand_name`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table structure for `valve_io_sizes`
DROP TABLE IF EXISTS `valve_io_sizes`;
CREATE TABLE `valve_io_sizes` (
  `id` int NOT NULL AUTO_INCREMENT,
  `inlet_size` varchar(50) NOT NULL,
  `outlet_size` varchar(50) NOT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_combination` (`inlet_size`,`outlet_size`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table structure for `valve_materials`
DROP TABLE IF EXISTS `valve_materials`;
CREATE TABLE `valve_materials` (
  `id` int NOT NULL AUTO_INCREMENT,
  `material_name` varchar(100) NOT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `material_name` (`material_name`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table structure for `valve_models`
DROP TABLE IF EXISTS `valve_models`;
CREATE TABLE `valve_models` (
  `id` int NOT NULL AUTO_INCREMENT,
  `model_name` varchar(100) NOT NULL,
  `brand_id` int DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `brand_id` (`brand_id`),
  CONSTRAINT `valve_models_ibfk_1` FOREIGN KEY (`brand_id`) REFERENCES `valve_brands` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table structure for `valve_serials`
DROP TABLE IF EXISTS `valve_serials`;
CREATE TABLE `valve_serials` (
  `id` int NOT NULL AUTO_INCREMENT,
  `equipment_no` varchar(100) NOT NULL,
  `serial_number` varchar(100) NOT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_serial` (`equipment_no`,`serial_number`),
  KEY `idx_equipment_no` (`equipment_no`)
) ENGINE=InnoDB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Table structure for `valve_set_pressures`
DROP TABLE IF EXISTS `valve_set_pressures`;
CREATE TABLE `valve_set_pressures` (
  `id` int NOT NULL AUTO_INCREMENT,
  `set_pressure` decimal(10,2) NOT NULL,
  `input_pressure` decimal(10,2) NOT NULL,
  `is_active` tinyint(1) DEFAULT '1',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = 1;
COMMIT;
